[workspace]

resolver = "2"
members = [
    "src/day1",
    "src/day2",
    "src/day3",
    "src/day4",
    "src/day5",
    "src/day6",
    "src/day7",
    "src/day9",
    "src/day10",
    "utils",
]

